baseURL: "https://outofscope.blog"
languageCode: "en-us"
title: "Everything beyond the brief"
timeZone: Europe/Berlin
summaryLength: 50
paginate: 12
canonifyURLs: false
footnoteReturnLinkContents: "↩"
plainIDAnchors: true
autolink: false
assetDir: "static"
permalinks:
  posts:  /posts/:slug
  notes:  /notes/:2006:01:02:150405
  links:  /:sections/:2006:01:02:150405
  photos: /photos/:2006/:01/:slug
taxonomies:
  tag: tags
  type: type
  language: lang

frontmatter:
  date:
    - "date"
    - "lastmod"
    - "publishDate"
    - ":filename"
  publishDate:
    - "date"
    - "publishDate"
  lastmod:
    - "lastmod"
    - ":fileModTime"
    - "publishDate"

markup:
  goldmark:
    parser:
      attribute:
        block: true
      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: true
      unsafe: true
# if you want markdown WYSIWYG line break
#blackfriday:
#  extensions:
#    - "hardLineBreak"

params:
  author:
    given_name: "Jason"
    family_name: "Friedrich"
    display_name: "Jason Friedrich"
    website: "https://friedrich.uk"
    fediverse_handle: "@jason@click.ba.it"
  email: "mail@outofscope.blog"
  friendly_url: outofscope.blog

caches:
  images:
    dir: :cacheDir/images

privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: false
    simple: false
  x:
    disable: false
    enableDNT: true
    simple: false
    disableInlineCSS: true
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

ignoreErrors: error-remote-getjson
